name: Jtay_Biz_Card
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.10
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/jtay.jpg

  fonts:
  - family: RobotoMono
    fonts:
    - asset: fonts/RobotoMono-Regular.ttf
  - family: BreeSerif
    fonts:
    - asset: fonts/BreeSerif-Regular.ttf